Repository census-instrumentation/opencensus-specs, pull requests merged in 2019-03, with the labels that each got.

#233 update Tag definition with TagMetadata.
  tags/TagMap.md
Labels: cla: yes, tags

#239 Fix TagMap links
  encodings/BinaryEncoding.md
  tags/README.md
Labels: cla: yes

#245 Encodings: Add readme.
  encodings/BinaryEncoding.md
  encodings/README.md
Labels: cla: yes, tags, trace

#250 TagMap : Change header key name from opencensus-tag-bin to grpc-tags-bin
  tags/TagMap.md
Labels: cla: yes

#235 Add a list of standard supported resources.
  resource/Resource.md
  resource/StandardResources.md
Labels: cla: yes
